hassio-addons/addon-unifi

- README.md
Documentation addition
had to walk 3 people though this in one night on discord
> added a work around to the hung adoption issue

- unifi/Dockerfile
Updated Unifi Controller to 5.10.21.
> Update to 5.10.21

- unifi/Dockerfile
> Update Unifi Controller to 5.10.24
> #39
> Bump Unifi Controller to 5.10.24

- unifi/Dockerfile
Upgrade UniFi Controller to 5.11.46
> :arrow_up: Upgrades UniFi Controller to 5.11.46

- unifi/Dockerfile
Upgrade UniFi Controller to 5.11.47
> :arrow_up: Upgrades UniFi Controller to 5.11.47

- unifi/Dockerfile
Upgrades UniFi Controller to 5.11.50
> :arrow_up: Upgrades UniFi Controller to 5.11.50

- README.md
Minor update to clarify memory_init
fixes #54
> 📚Minor update to readme

- unifi/Dockerfile
Upgrades Controller to latest stable release: https://community.ui.com/releases/UniFi-Network-Controller-5-12-22/263c8b60-def8-4667-85c3-87a6200a6c9b
<blockquote><img src="https://community.ui.com/images/og-image.jpg" width="48" align="right"><div><img src="https://prd-www-cdn.ubnt.com/static/favicon.ico" height="14"> Ubiquiti Community</div><div><strong><a href="http://community.ui.com/releases/UniFi-Network-Controller-5-12-22/263c8b60-def8-4667-85c3-87a6200a6c9b">5.12.22 | Ubiquiti Community</a></strong></div></blockquote>
> ⬆️ Upgrades UniFi Controller to 5.12.22

- README.md
Since I struggled to get adoption to work I added a small section about the settings needed the manual SSH way
> add information about device adoption

- unifi/Dockerfile
Tests have not been done!
Changelog: https://community.ui.com/releases/UniFi-Network-Controller-5-12-66/ac49e57b-6f38-4912-8455-940d3d487d00
> :arrow_up: Upgrade UniFi Controller to 5.12.66

- unifi/Dockerfile
Release notes:
https://community.ui.com/releases/UniFi-Network-Controller-5-12-72/9ac72983-5130-4f58-b3ba-909f4d4bb5f9
<blockquote><img src="https://community.ui.com/images/og-image.jpg" width="48" align="right"><div><img src="https://prd-www-cdn.ubnt.com/static/favicon.ico" height="14"> Ubiquiti Community</div><div><strong><a href="http://community.ui.com/releases/UniFi-Network-Controller-5-12-72/9ac72983-5130-4f58-b3ba-909f4d4bb5f9">5.12.72 | Ubiquiti Community</a></strong></div></blockquote>
> Update Unifi Controller to 5.12.72

- unifi/Dockerfile
**Update controller to 5.14.23**
Release notes: https://community.ui.com/releases/UniFi-Network-Controller-5-14-23/daf90732-30ad-48ee-81e7-1dcb374eba2a
> ⬆️ Upgrades UniFi Network Controller to 5.14.23

- unifi/Dockerfile
Upgrade UniFi Controller to v6.0.28 for bug fixes I've had.
https://community.ui.com/releases/UniFi-Network-Controller-6-0-28/23c77a99-0957-449a-b3c0-58a37d4df81f
> ⬆️ Upgrade UniFi Controller to v6.0.28

- LICENSE.md
- README.md
- unifi/.README.j2
- unifi/DOCS.md
> Happy New Year

- unifi/Dockerfile
- unifi/build.json
Release notes: <https://github.com/hassio-addons/addon-ubuntu-base/releases/tag/v6.0.0>
> Upgrade add-on base image to 6.0.0

- unifi/Dockerfile
Upgrades to the latest version of Unifi Controller
Changelog: https://community.ui.com/releases/UniFi-Network-Controller-6-0-45/8d3b98e1-b9d4-4ab3-b8da-721dbe9ab842
/
> ⬆️ Upgrade UniFi Controller v6.0.45

- unifi/Dockerfile
- unifi/build.json
Upgrades add-on base image to 6.1.2
https://github.com/hassio-addons/addon-ubuntu-base/releases/tag/v6.1.2
fixes #156
> Upgrade add-on base image to 6.1.2

- unifi/Dockerfile
- unifi/build.json
Upgrade add-on base image to 6.1.3
> Upgrade add-on base image to 6.1.3

- unifi/Dockerfile
Upgrades binutils to 2.30-21ubuntu1~18.04.5
> :arrow_up: Upgrades binutils to 2.30-21ubuntu1~18.04.5

- unifi/Dockerfile
Upgrading to latest unifi controller version
> ⬆ Upgrade UniFi Controller version 6.1.71

- unifi/Dockerfile
- unifi/build.json
Upgrades add-on base image to v6.1.4
> ⬆️  Upgrades add-on base image to v6.1.4

- unifi/rootfs/etc/cont-init.d/unifi.sh
Addresses a shellcheck linter warning that showed up due to upgrading shellcheck.
> Address shellcheck lint warning

- unifi/Dockerfile
- unifi/build.json
Upgrades add-on base image to v6.2.0
> ⬆️ Upgrades add-on base image to v6.2.0

- unifi/translations/en.yaml
> Add translation support

- unifi/rootfs/etc/cont-init.d/unifi.sh
To prevent writing to a readonly marked variable.
> Fix root chain

- unifi/Dockerfile
- unifi/build.json
Upgrades add-on base image to v6.2.1
> ⬆️ Upgrades add-on base image to v6.2.1

- unifi/Dockerfile
Fixes https://github.com/hassio-addons/addon-unifi/issues/231
> Update Unifi to 6.2.26 (released to GA, https://community.ui.com/releases/UniFi-Network-Application-6-2-26/0dfcbc77-8a4f-4e20-bb93-07bbb0237e3a)
> ⬆ Upgrade UniFi Controller to 6.2.26

- README.md
- unifi/Dockerfile
- unifi/build.json
- unifi/config.json
This PR drops support for 32-bits systems as announced in the previous release
and removes the workarounds for making it work on those systems.
> 🔥 Drop support for 32-bits systems (armv7, i386)

- README.md
- unifi/.README.j2
With the removal of the 32-bits hacks and the SSL workarounds, I'm confident to call this stable / 1.0.0.
> ✏️ Mark add-on stable

- unifi/Dockerfile
Upgrades binutils to 2.30-21ubuntu1~18.04.7
> ⬆️ Upgrades binutils to 2.30-21ubuntu1~18.04.7

- unifi/Dockerfile
Upgrades libssl1.0.0 to 1.0.2n-1ubuntu5.7
> ⬆️ Upgrades libssl1.0.0 to 1.0.2n-1ubuntu5.7

- unifi/Dockerfile
[> (Describe the changes and rationale behind them)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/](https://community.ui.com/releases/UniFi-Network-Application-6-4-54/c1be3b7f-44c4-4d6f-af1e-707bf017110d)
> ⬆️ Upgrades UniFi Network Application to v6.4.54

- README.md
- unifi/.README.j2
- unifi/DOCS.md
- unifi/rootfs/etc/cont-init.d/unifi.sh
- unifi/rootfs/etc/services.d/unifi/finish
- unifi/rootfs/etc/services.d/unifi/run
- unifi/translations/en.yaml
To follow up on the name change upstream
> Rebrand Controller -> Network Application

- unifi/DOCS.md
Unifi uses different wording in their UI atm than is reflected on the docs. This update should reduce confusion for other users.
> New wording for "Inform Host" in unifi settings

- unifi/Dockerfile
- unifi/build.yaml
Upgrades add-on base image to 7.1.3
> ⬆️ Upgrades add-on base image to 7.1.3

- unifi/Dockerfile
Upgrade UniFi Network Application to  v6.5.53
https://community.ui.com/releases/UniFi-Network-Application-6-5-53/16025ec1-4bbc-46a9-8f4f-8561fd59cd4c
> ⬆️ Upgrades UniFi Network Application to v6.5.53

- unifi/Dockerfile
UniFi release info: https://community.ui.com/releases/UniFi-Network-Application-6-5-54/d717f241-48bb-4979-8b10-99db36ddabe1
>  ⬆️ Upgrades UniFi Network Application to v6.5.54 (#318)

- unifi/Dockerfile
Now Stable: https://community.ui.com/releases/UniFi-Network-Application-6-5-55/48c64137-4a4a-41f7-b7e4-3bee505ae16e#comment/03156c88-7b05-4d26-87b3-bb1da5b2f0d9
closes #325
> ⬆️ Upgrades UniFi Network Application to v6.5.5

- unifi/Dockerfile
- unifi/build.yaml
Upgrades add-on base image to 7.1.4
> ⬆️ Upgrades add-on base image to 7.1.4

- unifi/DOCS.md
The new Unifi UI changed some options, updating docs to match.
> 📚 Update Inform Host instructions for new UI

- unifi/Dockerfile
Upgrade UniFi Network Application to v7.0.23
- Release Thread: https://community.ui.com/releases/UniFi-Network-Application-7-0-23/f1b404b4-f595-4346-aaa1-df6941e35525
- Promotion to stable: https://community.ui.com/releases/UniFi-Network-Application-7-0-23/f1b404b4-f595-4346-aaa1-df6941e35525#comment/7a547fe7-1a7c-41a7-9960-948458e9d113
> ⬆️ Upgrades UniFi Network Application to v7.0.23

- unifi/Dockerfile
- unifi/build.yaml
Upgrades add-on base image to 7.2.0
> ⬆️ Upgrades add-on base image to 7.2.0

- .github/workflows/deploy.yaml
- unifi/build.yaml
- unifi/config.yaml
Sign add-on with Codenotary Community Attestation Service (CAS)
> :lock: Sign add-on with Codenotary Community Attestation Service (CAS)

- unifi/DOCS.md
Add My buttons to documentation
> :books: Add My buttons to documentation

- unifi/DOCS.md
Not sure when these changed, however updating the docs to reference the config.
Update memory options in docs.
> 📚 Update details on memory usage

- unifi/Dockerfile
* update to Network Application 7.0.25
https://community.ui.com/releases/UniFi-Network-Application-7-0-25/3344c362-7da5-4ecd-a403-3b47520e3c01
> ⬆️ Upgrades UniFi Network Application to 7.0.25

- unifi/Dockerfile
> [Update to Network Application 7.1.61](https://community.ui.com/releases/UniFi-Network-Application-7-1-61/06f67c89-c798-423f-91a2-4cb2bca7694d)
> ⬆️ Upgrades UniFi Network Application to 7.1.61

- unifi/Dockerfile
- unifi/build.yaml
- unifi/rootfs/etc/cont-init.d/unifi.sh
- unifi/rootfs/etc/services.d/unifi/finish
- unifi/rootfs/etc/services.d/unifi/run
Upgrades add-on base image to 8.0.0
> ⬆️ Upgrades add-on base image to 8.0.0

- unifi/DOCS.md
Making things a tiny bit easier
> :books: Use new My Home Assistant link format

- unifi/Dockerfile
- unifi/build.yaml
> ⬆️ Upgrades add-on base image to 8.1.0

- unifi/Dockerfile
Upgrade unifi controller version to 7.1.68
None
> ⬆️ Upgrades UniFi Network Application to 7.1.68

- unifi/DOCS.md
- unifi/Dockerfile
update to latest stable version 7.2.92
See more info about release here:
https://community.ui.com/releases/UniFi-Network-Application-7-2-92/f1903cbc-4daa-4695-ac8c-7324bcff529a
or
https://www.reddit.com/r/UNIFI/comments/wj49lt/unifi_network_application_7292/
> ⬆️ Upgrades UniFi Network Application to 7.2.92

- unifi/Dockerfile
https://community.ui.com/releases/UniFi-Network-Application-7-2-94/2ab774d1-0f24-422e-accc-53b8200c10a7
> Upgrades UniFi Network Application to 7.2.94

- unifi/Dockerfile
- unifi/build.yaml
> ⬆️ Upgrades add-on base image to 8.1.2

- unifi/Dockerfile
https://community.ui.com/releases/UniFi-Network-Application-7-2-95/7adebab5-8c41-4989-835d-ab60dba55255
> ⬆️ Upgrades UniFi Network Application to v7.2.95

- unifi/Dockerfile
- unifi/build.yaml
Upgrades the add-on base image to the latest, allowing to migrate the s6 legacy style scripts in a next PR.
> ⬆️ Upgrades add-on base image to 82.0

- unifi/Dockerfile
Upgrades the UniFi Network Application to v7.3.76
<https://community.ui.com/releases/UniFi-Network-Application-7-3-76/85c75fc7-3e0f-4e99-aa90-7068af4f1141>
> ⬆️ Upgrades UniFi Network Application to v7.3.76

- unifi/Dockerfile
Adds a Docker healthcheck, allowing to Home Assistant Supervisor Watchdog to monitor this add-on better (and quicker).
> :stethoscope: Add healthcheck to improve HA watchdog

- unifi/DOCS.md
Updated Installation steps to match the menu of the latest UI version
> 📚 Update docs to match latest UniFi interface

- unifi/Dockerfile
> update unifi to version 7.3.83
> https://community.ui.com/releases/UniFi-Network-Application-7-3-83/88f5ff3f-4c13-45e2-b57e-ad04b4140528
> ⬆️ Upgrades UniFi Network Application to 7.3.83

- unifi/Dockerfile
> ⬆️ Upgrades openjdk-11-jdk-headless to 11.0.18+10-0ubuntu1~20.04.1

- unifi/Dockerfile
> ⬆️ Upgrades binutils to 2.34-6ubuntu1.6

- unifi/Dockerfile
> ⬆️ Upgrades openjdk-11-jdk-headless to 11.0.19+7~us1-0ubuntu1~20.04.1

- unifi/Dockerfile
Update the Unifi Network Application to the latest version, see the release notes [here](https://community.ui.com/releases/UniFi-Network-Application-7-4-156/15ac6260-9cd1-4ac3-a91c-4880c1c87882)
> ⬆️ Upgrades UniFi Network Application to 7.4.162

- unifi/rootfs/etc/s6-overlay/s6-rc.d/unifi/run
> Finetune UniFi

- unifi/Dockerfile
Update to latest build - 7.5.187
https://community.ui.com/releases/UniFi-Network-Application-7-5-187/408b64c5-a485-4a37-843c-31e87140be64
> Web-UI was showing update available for Network Application. Have updated appropriately and linked to change log.
> Update to 7.5.187

- unifi/Dockerfile
Update network application version to version 8.0.7
> ⬆️ Upgrades UniFi Network Application to 8.0.7

- unifi/Dockerfile
Bumped version to 8.0.24
> version bumped to 8.0.24
> Version update to 8.0.24

- unifi/translations/fr.yaml
> FR translation for configuration
> 🌎 FR translations

- LICENSE.md
- README.md
- unifi/.README.j2
- unifi/DOCS.md
> :fireworks: Updates maintenance/license year to 2024

- unifi/Dockerfile
https://community.ui.com/releases/UniFi-Network-Application-8-0-26/cd9303a8-f26a-44e2-94d8-a3cac8606726
> ⬆️ Upgrades UniFi Network Application to v8.0.26

- unifi/translations/pt-BR.yaml
Initial pt-BR translation
None
> Add pt-BR translation

- unifi/DOCS.md
Fix for #482.
Rewrote step 7 to avoid ambiguity about final state of checkbox
Issues described in #482
> Improve DOCS.md

- unifi/Dockerfile
Rel notes: https://community.ui.com/releases/UniFi-Network-Application-8-1-127/571d2218-216c-4769-a292-796cff379561
> ⬆️ Upgrades UniFi Network Application to 8.1.127

- unifi/Dockerfile
Rel notes: https://community.ui.com/releases/UniFi-Network-Application-8-2-93/fce86dc6-897a-4944-9c53-1eec7e37e738
> ⬆️ Upgrades UniFi Network Application to 8.2.93

- unifi/Dockerfile
> :arrow_up: Upgrades binutils to 2.34-6ubuntu1.11
