hassio-addons/addon-unifi

unifi/config.json
Some might use for external monitoring applications.
> Added port 161 in the container.
> None
=> Added SNMP port as an option.

unifi/Dockerfile
Update the Unifi controller to version 5.12.35
=> :arrow_up: Upgrade UniFi Controller to 5.12.35

unifi/Dockerfile
Release notes: https://community.ui.com/releases/UniFi-Network-Controller-5-13-32/85eee834-c987-4875-8de2-51c6842d7bd3
DL url confirmed working
<blockquote><img src="https://community.ui.com/images/og-image.jpg" width="48" align="right"><div><img src="https://prd-www-cdn.ubnt.com/static/favicon.ico" height="14"> Ubiquiti Community</div><div><strong><a href="http://community.ui.com/releases/UniFi-Network-Controller-5-13-32/85eee834-c987-4875-8de2-51c6842d7bd3">5.13.32 | Ubiquiti Community</a></strong></div></blockquote>
=> Update unifi controller to 5.13.32

unifi/Dockerfile
6.0.23 has a bug where VLANs behind a UAP downlink won't connect. This is affecting one of my installations. It was fixed in 6.0.26, but there are other various bugfixes in 6.0.27
https://community.ui.com/releases/UniFi-Network-Controller-6-0-26/7298f408-d9bf-48d7-b92c-a29c5b73b769
https://community.ui.com/releases/UniFi-Network-Controller-6-0-27/969b5662-b647-4e11-84cc-a10857a8ece5
=> :arrow_up: Upgrades UniFi Controller to v6.0.27

unifi/Dockerfile
Upgrade UniFi Controller to v6.0.36
https://community.ui.com/releases/UniFi-Network-Controller-6-0-36/9e57165b-3422-4fcf-ae02-13affcb388c8
=> ⬆️ Upgrade UniFi Controller v6.0.36

unifi/Dockerfile
Upgraded Controller to v6.0.41
Release notes:
https://community.ui.com/releases/UniFi-Network-Controller-6-0-41/25633411-0273-4197-bf30-4aff30b3701e
=> ⬆️ Upgrade UniFi Controller v6.0.41

unifi/Dockerfile
Upgrade UniFi Controller v6.0.43
Release notes:
[Link](https://community.ui.com/releases/UniFi-Network-Controller-6-0-43/b28bb453-927a-4dd8-82f7-40af28505510)
Installed and working on fresh HA
=> ⬆️ Upgrade UniFi Controller v6.0.43

unifi/Dockerfile, unifi/build.json
Upgrades the add-on base image to 6.1.1
Release notes: <https://github.com/hassio-addons/addon-ubuntu-base/releases/tag/v6.1.1>
=> Upgrade add-on base image to 6.1.1

unifi/Dockerfile
Upgrades openjdk-8-jdk-headless to 8u282-b08-0ubuntu1~18.04
=> :arrow_up: Upgrades openjdk-8-jdk-headless to 8u282-b08-0ubuntu1~18.04

unifi/Dockerfile
Upgrades openjdk-8-jdk-headless to 8u292-b10-0ubuntu1~18.04
=> ⬆️ Upgrades openjdk-8-jdk-headless to 8u292-b10-0ubuntu1~18.04

unifi/Dockerfile
As of today this RC went to stable
https://community.ui.com/releases/UniFi-Network-Application-6-2-23/df89533b-184a-4fb7-b2c6-9f894b82df27#comment/85dcd21f-84b6-4967-bb8a-2ea349ead55e
> update version from 6.1.71 to 6.2.23
Tested ok in HA LAB environment(esxi)
fixes #196
fixes #189
fixes #180
=> ⬆ Upgrade UniFi Controller 6.2.23

README.md, unifi/Dockerfile
Upgrade to [latest stable controller release](https://community.ui.com/releases/UniFi-Network-Application-6-2-25/d9cb0897-3ef4-4dda-a5d6-c07530ff8a86)
The current version, 6.2.23, is causing many issues. I think everything is related to this note under [known issues for the 6.2.23 release](https://community.ui.com/releases/UniFi-Network-Application-6-2-23/df89533b-184a-4fb7-b2c6-9f894b82df27): 
`You may experience a migration issue when upgrading from 6.1.71 to 6.2.23. You can upgrade to 6.2.17 before 6.2.23 as a workaround.`
The previous version for this addon was 6.1.71, so we skipped 6.2.17, which aligns with the database migration errors described by Ubiquiti.
I don't see any known issues or required versions in the upgrade notes for 6.2.25, and both the current add-on release …
=> Upgrade controller to 6.2.25

unifi/DOCS.md, unifi/config.json, unifi/rootfs/etc/cont-init.d/unifi.sh, unifi/translations/en.yaml
This PR drops support for custom SSL certificates. Handling them is problematic and has caused issues.
From this moment on the add-on will use a self-signed certificate (which will be migrated to if you have used a custom certificate before).
If you want to use a custom certificate, we would recommend using a reverse proxy in front of the UniFi Controller add-on.
fixes #235
fixes #239
fixes #205
=> 🔥 Drop support for custom SSL certificates

unifi/Dockerfile
In order to provide a viable upgrade path for existing installations, this PR forces the installation of MongoDB 3.4.
This makes MongoDB take care of the migration. In a few months, this can be reverted, making the step to upgrade to MongoDB 3.6.
=> ⬇️  Downgrade MongoDB to 3.4 to provide an upgrade path

unifi/config.json
Rename `snapshot` to `backup`.
See : https://developers.home-assistant.io/blog/2021/08/24/supervisor_update/
Fixes #263
=> snapshot -> backup

README.md, unifi/DOCS.md
I read https://github.com/hassio-addons/addon-unifi/issues/251 and I agree with @e28eta . While Raspberry Pi still is a supported platform, I think it is wrong to say that all architectures supported by Home Assistant are supported by this add-on. As far as I can see there are 3 architectures listed as not supported in the badge-list (armhf, armv7, i386).
I think just removing the line saying that all architectures are supported would be enough. I checked the [vscode add-on](https://github.com/hassio-addons/addon-vscode/) and there are no specifics mentioned there, so this will make this add-on similar.
Since the dropped 32-bit support is a recent change I suggest adding a line for that in the README, this might avoid some questions or opened issues. But of course this is totally up to …
=> Updates to documentation after dropped 32-bit support

unifi/Dockerfile, unifi/build.yaml
Upgrade the add-on base image to 7.1.2 (Ubuntu Focal).
This also switches to the MongoDB server to MongoDB 3.6, which is shipped with Ubuntu itself.
=> ⬆️ Upgrades add-on base image to 7.1.2

unifi/rootfs/etc/services.d/unifi/run
Add a small tweak/additional log message to the start-up log, as users expect more to show up.
Unfortunately, UniFi doesn't log much more, so it seems "stuck", while you can't tell...
=> Improve clarity about last log message

unifi/Dockerfile
Updating this dependency, since we can't build the image anymore because the previous version doesn't exist in the repository anymore.
Build logs before : 
```
21-12-19 19:32:14 INFO (SyncWorker_5) [supervisor.docker.interface] Removing image local/amd64-addon-unifi with latest and None
21-12-19 19:32:14 INFO (SyncWorker_2) [supervisor.docker.addon] Starting build for local/amd64-addon-unifi:dev
21-12-19 19:32:22 ERROR (SyncWorker_2) [supervisor.docker.addon] Can't build local/amd64-addon-unifi:dev: The command '/bin/bash -o pipefail -c apt-get update     && apt-get install -y --no-install-recommends         binutils=2.34-6ubuntu1.3         jsvc=1.0.15-8         libcap2=1:2.32-1         logrotate=3.14.0-4ubuntu3         mongodb-server=1:3.6.9+really3.6.8+90~g8e540c0b6d-0ubuntu5.3 …
```
=> ⬆️ Update openjdk-8-jdk-headless to 8u312-b07-0ubuntu1~20.04

unifi/DOCS.md
Remove the migrating to section, to avoid the complexity of maintaining links to changing upstream sites.
closes #350
closes #348
=> 📚 Remove migrating section

unifi/Dockerfile
The following fixes for UniFi Network Application since 7.1.61:
Bugfixes
Fix memory leak affecting users using a self-hosted version of the Network application and using VPN features.
Fix rare issue applying configuration on UXG Pro.
Fix USW adoption issue due to a invalid IP subnet configuration for L3 Networks/Static Routes.
Fix a rare issue where sometimes UXG-Pro adoption does not work.
Fix various issues with creating/editing traffic rules/routes.
Known issues
Image for the USG-Pro-4 in the dashboard is missing.
> Upgrade .deb path for 7.1.65 now its released.
> [UniFi 7.1.65 Release Announcement](https://community.ui.com/releases/UniFi-Network-Application-7-1-65/)
[autolink-references]: …
=> ⬆️ Upgrades UniFi Network Application to 7.1.65

unifi/Dockerfile
The following fixes for UniFi Network Application since 7.1.65:
**Improvements**
Improve application stability when using mobile apps.
**Known issues**
Image for the USG-Pro-4 in the dashboard is missing, fixed in 7.2.
> Upgrade .deb path for 7.1.66 now its released.
> [UniFi 7.1.66 Release Announcement](https://community.ui.com/releases/UniFi-Network-Application-7-1-66/cf1208d2-3898-418c-b841-699e7b773fd4)
=> ⬆️ Upgrades UniFi Network Application to 7.1.66

unifi/Dockerfile
It seems that newer UniFi Network Application versions require the log folder to exist (or the application gets into a limbo state, serving only 404s or getting stuck in database migration).
This PR adjusts the cleanup in our Dockerfile to be less aggressive (and keeps the folders around).
=> :ambulance: Fix missing log folders causing crash

unifi/Dockerfile
> Update Dockerfile to pull Unifi controller 7.5.176 and OpenJDK 17.
=> Bump Unifi controller to 7.5.176 (latest)

unifi/DOCS.md
I was reading the doc and found some incorrect markdown formatting. It appears this was a copy-paste error from the `README.md` which used to contain a similar text.
Just a small fix for the formatting :)
=> Fix markdown formatting in documentation

unifi/Dockerfile
Updating controller to released version 8.0.28 on 25th Jan 2024.
New Network controller version released on 25th Jan 2024.
=> Update Network controller to version 8.0.28

unifi/Dockerfile
This PR does various improvements to the Dockerfile:
- removes unneeded package, which reduces the image size by about 10%
- run apt-get upgrade to get the latest security updates
- ~~improve the way package version are specified in apt-get install so that this line does not have to be updated every time one of these packages is updated~~
=> Dockerfile improvements

unifi/Dockerfile, unifi/build.yaml, unifi/rootfs/etc/s6-overlay/s6-rc.d/init-unifi/run
This switches from ubuntu-base:8 to ubuntu-base:9 as the base image (ie ubuntu 20.04 to ubuntu 22.04).
The main complication is mongodb, it's now installed from mongodb community servers as it's gone from newer ubuntu repositories. Beware of the licence change, previously the addon used mongodb version 3.6.9 released under the AGPL, while 4.0.3 and newer are released under the non-free SSPL
https://en.wikipedia.org/wiki/MongoDB#Licensing
Installing mongodb 4.4 which is compatible with the unifi package requires some hackish install of the appropriate libssl.
mongodb 7.0 is easier to install, but requires the use of `--ignore-depends=mongodb-org-server` when installing the unifi package.
I couldn't make my mind regarding which option is best, so it's easy to pick one or the other by …
=> Update base image to ubuntu-base:9.0.4

unifi/Dockerfile
> Update controller to 8.1.133 (current). Tested locally.
=> Update controller to 8.1.133

unifi/Dockerfile, unifi/build.yaml, unifi/rootfs/etc/s6-overlay/s6-rc.d/init-unifi/run
Reverts hassio-addons/addon-unifi#491
As this breaks existing installations. The new MongoDB version removes the deprecated mmap engine, and makes WiredTiger the new default. However, the PR listed, doesn't take that into account (no migration).
This shipping this, would break the add-on.
/CC @cfergeau
=> Revert "Update base image to ubuntu-base:9.0.4"

unifi/Dockerfile
Pinning binutils from 2.34-6ubuntu1.8 to 2.34-6ubuntu1.9.
=> Pin binutils to 2.34-6ubuntu1.9

unifi/Dockerfile
Bump version to 9.1.120 (released 25 April)
https://www.ui.com/download/releases/network-server
=> ⬆️ Upgrades UniFi Network Application to 9.1.120
